# Generated by Django 5.1.15 on 2026-07-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sigla', models.CharField(help_text='Código curto usado na grade (ex.: MAT, POR, HIST).', max_length=10, unique=True, verbose_name='Sigla')),
                ('quantidade_aulas_semana', models.PositiveSmallIntegerField(default=1, help_text='Quantas aulas desta disciplina cada turma tem por semana.', verbose_name='Aulas por semana')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['nome'],
            },
        ),
    ]
