# Generated by Django 5.1.15 on 2026-07-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='tipo_ambiente',
            field=models.CharField(blank=True, choices=[('SALA', 'Sala'), ('BIBLIOTECA', 'Biblioteca'), ('LABORATORIO', 'Laboratório'), ('QUADRA', 'Quadra'), ('AUDITORIO', 'Auditório'), ('MAKER', 'Maker')], help_text='Deixe em branco para usar uma sala comum. Preencha somente quando esta disciplina sempre precisar de um ambiente específico (ex.: Laboratório, Quadra) — o Módulo 11 (algoritmo automático) usa este dado para escolher o ambiente certo de cada aula.', max_length=20, null=True, verbose_name='Tipo de ambiente necessário'),
        ),
    ]
