# Generated by Django 5.1.15 on 2026-07-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(help_text='Posição deste horário na grade do dia (1, 2, 3...).', unique=True, verbose_name='Ordem')),
                ('inicio', models.TimeField(verbose_name='Início')),
                ('fim', models.TimeField(verbose_name='Fim')),
                ('intervalo', models.BooleanField(default=False, help_text='Marque se este período é um intervalo, não uma aula.', verbose_name='É intervalo/recreio')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Horário',
                'verbose_name_plural': 'Horários',
                'ordering': ['ordem'],
            },
        ),
    ]
