# Generated by Django 5.1.15 on 2026-07-28 10:30

import apps.grade.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambientes', '0001_initial'),
        ('disciplinas', '0001_initial'),
        ('horarios', '0001_initial'),
        ('professores', '0001_initial'),
        ('turmas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('SEGUNDA', 'Segunda-feira'), ('TERCA', 'Terça-feira'), ('QUARTA', 'Quarta-feira'), ('QUINTA', 'Quinta-feira'), ('SEXTA', 'Sexta-feira')], max_length=10, verbose_name='Dia da semana')),
                ('ano_letivo', models.PositiveIntegerField(default=apps.grade.models.ano_letivo_padrao, verbose_name='Ano letivo')),
                ('semestre', models.CharField(choices=[('1', '1º Semestre'), ('2', '2º Semestre')], default='1', max_length=1, verbose_name='Semestre')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aulas', to='ambientes.ambiente', verbose_name='Ambiente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aulas', to='disciplinas.disciplina', verbose_name='Disciplina')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='horarios.horario', verbose_name='Horário')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aulas', to='professores.professor', verbose_name='Professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='turmas.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Aula da grade',
                'verbose_name_plural': 'Aulas da grade',
                'ordering': ['ano_letivo', 'semestre', 'turma__nome', 'dia_semana', 'horario__ordem'],
                'constraints': [models.UniqueConstraint(fields=('turma', 'dia_semana', 'horario', 'ano_letivo', 'semestre'), name='grade_turma_sem_dupla_aula_no_mesmo_horario'), models.UniqueConstraint(fields=('professor', 'dia_semana', 'horario', 'ano_letivo', 'semestre'), name='grade_professor_sem_duas_turmas_ao_mesmo_tempo')],
            },
        ),
    ]
