# Generated by Django 5.1.15 on 2026-07-28 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0002_disciplina_tipo_ambiente'),
        ('grade', '0001_initial'),
        ('professores', '0001_initial'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='disciplinas.disciplina', verbose_name='Disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='professores.professor', verbose_name='Professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='turmas.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Atribuição de professor',
                'verbose_name_plural': 'Atribuições de professores',
                'ordering': ['turma__nome', 'disciplina__nome'],
                'constraints': [models.UniqueConstraint(fields=('turma', 'disciplina'), name='atribuicao_unica_por_turma_disciplina')],
            },
        ),
    ]
