# Generated by Django 5.1.15 on 2026-07-28 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255, unique=True, verbose_name='Nome do arquivo')),
                ('tamanho_bytes', models.BigIntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora')),
                ('criado_por', models.ForeignKey(blank=True, help_text='Em branco quando gerado pelo comando agendado (sem usuário logado).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_gerados', to=settings.AUTH_USER_MODEL, verbose_name='Gerado por')),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'ordering': ['-criado_em'],
            },
        ),
    ]
