# Generated by Django 5.1.15 on 2026-07-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex.: 1º Ano A, 9º Ano B.', max_length=50, verbose_name='Nome')),
                ('serie', models.CharField(help_text='Ex.: 1º Ano, 9º Ano, 3ª Série.', max_length=50, verbose_name='Série')),
                ('turno', models.CharField(choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino'), ('NOTURNO', 'Noturno'), ('INTEGRAL', 'Integral')], max_length=20, verbose_name='Turno')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['serie', 'nome'],
                'constraints': [models.UniqueConstraint(fields=('nome', 'turno'), name='turma_nome_turno_unico')],
            },
        ),
    ]
