# Generated by Django 5.1.15 on 2026-08-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ['etapa_ensino', 'serie', 'nome'], 'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
        migrations.AddField(
            model_name='turma',
            name='etapa_ensino',
            field=models.CharField(choices=[('FUNDAMENTAL_1', 'Ensino Fundamental I (Anos Iniciais — 1º ao 5º ano)'), ('FUNDAMENTAL_2', 'Ensino Fundamental II (Anos Finais — 6º ao 9º ano)'), ('MEDIO', 'Ensino Médio (1º ao 3º ano)')], default='FUNDAMENTAL_2', help_text='Fundamental I, Fundamental II ou Médio, conforme a divisão do MEC/LDB.', max_length=20, verbose_name='Etapa de ensino'),
        ),
    ]
