# Generated by Django 5.1.15 on 2026-08-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_alter_turma_options_turma_etapa_ensino'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='codigo_evento',
            field=models.CharField(blank=True, help_text='Código interno que o SENAI atribui a esta turma/oferta específica do curso (sistema SGE).', max_length=30, verbose_name='Código do evento'),
        ),
        migrations.AddField(
            model_name='turma',
            name='curso_tecnico',
            field=models.CharField(blank=True, choices=[('ALIMENTOS', 'Técnico em Alimentos'), ('AUTOMACAO_INDUSTRIAL', 'Técnico em Automação Industrial'), ('DESENVOLVIMENTO_DE_SISTEMAS', 'Técnico em Desenvolvimento de Sistemas'), ('DESIGN_GRAFICO', 'Técnico em Design Gráfico'), ('EDIFICACOES', 'Técnico em Edificações'), ('ELETROMECANICA', 'Técnico em Eletromecânica'), ('ELETROTECNICA', 'Técnico em Eletrotécnica'), ('MANUTENCAO_AUTOMOTIVA', 'Técnico em Manutenção Automotiva'), ('MANUTENCAO_DE_MAQUINAS_INDUSTRIAIS', 'Técnico em Manutenção de Máquinas Industriais'), ('MANUTENCAO_E_SUPORTE_EM_INFORMATICA', 'Técnico em Manutenção e Suporte em Informática'), ('MECANICA', 'Técnico em Mecânica'), ('MECATRONICA', 'Técnico em Mecatrônica'), ('PROGRAMACAO_DE_JOGOS_DIGITAIS', 'Técnico em Programação de Jogos Digitais'), ('QUIMICA', 'Técnico em Química'), ('REDES_DE_COMPUTADORES', 'Técnico em Redes de Computadores'), ('VESTUARIO', 'Técnico em Vestuário')], help_text='Preencha somente quando a etapa de ensino for "Curso Técnico".', max_length=40, verbose_name='Curso técnico'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='etapa_ensino',
            field=models.CharField(choices=[('FUNDAMENTAL_1', 'Ensino Fundamental I (Anos Iniciais — 1º ao 5º ano)'), ('FUNDAMENTAL_2', 'Ensino Fundamental II (Anos Finais — 6º ao 9º ano)'), ('MEDIO', 'Ensino Médio (1º ao 3º ano)'), ('TECNICO', 'Curso Técnico (SENAI)')], default='FUNDAMENTAL_2', help_text='Fundamental I, Fundamental II, Médio ou Curso Técnico, conforme a divisão do MEC/LDB.', max_length=20, verbose_name='Etapa de ensino'),
        ),
    ]
