# Generated by Django 5.1.15 on 2026-08-07 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grade', '0002_atribuicao'),
        ('professores', '0002_professor_etapas_autorizadas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Substituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da substituição')),
                ('aula_cancelada', models.BooleanField(default=False, help_text='Marque quando não houve professor eventual disponível para cobrir a falta.', verbose_name='Aula cancelada (sem substituto)')),
                ('motivo', models.CharField(blank=True, help_text='Ex.: atestado médico, licença.', max_length=255, verbose_name='Motivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes', to='grade.gradeaula', verbose_name='Aula da grade')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituicoes_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('professor_substituto', models.ForeignKey(blank=True, help_text='Deixe em branco se a aula foi cancelada (sem atendimento pedagógico nesse dia).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substituicoes_como_substituto', to='professores.professor', verbose_name='Professor substituto')),
            ],
            options={
                'verbose_name': 'Substituição de professor',
                'verbose_name_plural': 'Substituições de professores',
                'ordering': ['-data'],
                'constraints': [models.UniqueConstraint(fields=('aula', 'data'), name='substituicao_unica_por_aula_e_data')],
            },
        ),
    ]
