# Generated by Django 5.1.15 on 2026-07-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex.: Laboratório de Informática, Quadra Poliesportiva.', max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('SALA', 'Sala'), ('BIBLIOTECA', 'Biblioteca'), ('LABORATORIO', 'Laboratório'), ('QUADRA', 'Quadra'), ('AUDITORIO', 'Auditório'), ('MAKER', 'Maker')], max_length=20, verbose_name='Tipo')),
                ('capacidade', models.PositiveSmallIntegerField(default=1, help_text='Quantas turmas podem usar este ambiente ao mesmo tempo (normalmente 1).', verbose_name='Capacidade de uso simultâneo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambientes',
                'ordering': ['tipo', 'nome'],
                'constraints': [models.UniqueConstraint(fields=('nome',), name='ambiente_nome_unico')],
            },
        ),
    ]
