# Generated by Django 5.1.15 on 2026-07-28 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horarios', '0001_initial'),
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadeProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('SEGUNDA', 'Segunda-feira'), ('TERCA', 'Terça-feira'), ('QUARTA', 'Quarta-feira'), ('QUINTA', 'Quinta-feira'), ('SEXTA', 'Sexta-feira')], max_length=10, verbose_name='Dia da semana')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='horarios.horario', verbose_name='Horário')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='professores.professor', verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Disponibilidade de professor',
                'verbose_name_plural': 'Disponibilidades de professores',
                'ordering': ['professor__nome', 'dia_semana', 'horario__ordem'],
                'constraints': [models.UniqueConstraint(fields=('professor', 'dia_semana', 'horario'), name='disponibilidade_unica_por_professor_dia_horario')],
            },
        ),
    ]
