# Generated by Django 5.1.15 on 2026-07-28 13:54

import apps.calendario.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('FERIADO', 'Feriado'), ('RECESSO', 'Recesso escolar'), ('PROVA', 'Prova/Avaliação'), ('EVENTO', 'Evento escolar'), ('REUNIAO', 'Reunião pedagógica'), ('OUTRO', 'Outro')], default='EVENTO', max_length=20, verbose_name='Tipo')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, help_text='Deixe em branco se o evento dura só um dia.', null=True, verbose_name='Data de fim')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('afeta_aulas', models.BooleanField(default=False, help_text='Marque para feriados e recessos — avisa quem consultar o calendário que não há aula.', verbose_name='Não há aula normal neste período')),
                ('ano_letivo', models.PositiveIntegerField(default=apps.calendario.models.ano_letivo_padrao, verbose_name='Ano letivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Evento do calendário',
                'verbose_name_plural': 'Eventos do calendário',
                'ordering': ['data_inicio', 'titulo'],
            },
        ),
    ]
