# Generated by Django 5.1.15 on 2026-08-07 19:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
        ('turmas', '0002_alter_turma_options_turma_etapa_ensino'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='etapas_autorizadas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('FUNDAMENTAL_1', 'Ensino Fundamental I (Anos Iniciais — 1º ao 5º ano)'), ('FUNDAMENTAL_2', 'Ensino Fundamental II (Anos Finais — 6º ao 9º ano)'), ('MEDIO', 'Ensino Médio (1º ao 3º ano)')], max_length=20), blank=True, default=list, help_text='Deixe em branco para não restringir por etapa (pode lecionar em turmas de qualquer etapa).', size=None, verbose_name='Etapas de ensino em que pode lecionar'),
        ),
        migrations.AddField(
            model_name='professor',
            name='turmas_bloqueadas',
            field=models.ManyToManyField(blank=True, help_text='Turmas específicas em que NÃO pode lecionar, mesmo pertencendo a uma etapa autorizada.', related_name='professores_bloqueados', to='turmas.turma', verbose_name='Turmas bloqueadas mesmo dentro da etapa'),
        ),
        migrations.AddField(
            model_name='professor',
            name='turmas_liberadas',
            field=models.ManyToManyField(blank=True, help_text='Turmas específicas em que pode lecionar mesmo fora das etapas marcadas acima.', related_name='professores_liberados', to='turmas.turma', verbose_name='Turmas liberadas além da etapa'),
        ),
    ]
