# Generated by Django 5.1.15 on 2026-07-28 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIACAO', 'Criação'), ('ATUALIZACAO', 'Atualização'), ('REMOCAO', 'Remoção'), ('LOGIN', 'Login'), ('LOGIN_FALHOU', 'Tentativa de login falhou'), ('LOGOUT', 'Logout')], max_length=20, verbose_name='Ação')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('objeto_id', models.CharField(blank=True, max_length=50, verbose_name='ID do objeto')),
                ('objeto_repr', models.CharField(blank=True, max_length=300, verbose_name='Descrição do objeto')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora')),
                ('usuario', models.ForeignKey(blank=True, help_text='Em branco quando a ação foi de um visitante não autenticado (ex.: login que falhou).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Registro de auditoria',
                'verbose_name_plural': 'Registros de auditoria',
                'ordering': ['-criado_em'],
            },
        ),
    ]
