# Generated by Django 5.1.15 on 2026-07-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='acao',
            field=models.CharField(choices=[('CRIACAO', 'Criação'), ('ATUALIZACAO', 'Atualização'), ('REMOCAO', 'Remoção'), ('RESTAURACAO', 'Restauração de backup'), ('LOGIN', 'Login'), ('LOGIN_FALHOU', 'Tentativa de login falhou'), ('LOGOUT', 'Logout')], max_length=20, verbose_name='Ação'),
        ),
    ]
